name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.12.0"
              otp: "22"
          - pair:
              elixir: "1.16"
              otp: "26"
            dialyze: dialyze
          - pair:
              elixir: "1.17"
              otp: "27"
            lint: lint
            dialyze: dialyze
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix credo

      - run: mix dialyzer
        if: ${{ matrix.dialyze }}

      - run: mix coveralls.json

      - uses: codecov/codecov-action@v4.0.1
        if: ${{ matrix.lint }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
